module.exports = {
  source: ['raw-tokens/sd-input.json'],
  fileHeader: {
    autoGeneratedFileHeader: () => {
      return [`Do not edit directly, this file was auto-generated`];
    },
  },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'Core/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: {
            fileHeader: 'autoGeneratedFileHeader',
          },
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'Core/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
          options: {
            fileHeader: 'autoGeneratedFileHeader',
          },
        },
      ],
    },
  },
};
